export const GET_WISHLIST_GET_REQUEST = "GET_WISHLIST_GET_REQUEST";
export const GET_WISHLIST_GET_SUCCESS = "GET_WISHLIST_GET_SUCCESS";
export const GET_WISHLIST_GET_FAILURE = "GET_WISHLIST_GET_FAILURE";

export const GET_WISHLIST_ADD_REQUEST = "GET_WISHLIST_ADD_REQUEST";
export const GET_WISHLIST_ADD_SUCCESS = "GET_WISHLIST_ADD_SUCCESS";
export const GET_WISHLIST_ADD_FAILURE = "GET_WISHLIST_ADD_FAILURE";

export const GET_WISHLIST_DELETE_REQUEST = "GET_WISHLIST_DELETE_REQUEST";
export const GET_WISHLIST_DELETE_SUCCESS = "GET_WISHLIST_DELETE_SUCCESS";
export const GET_WISHLIST_DELETE_FAILURE = "GET_WISHLIST_DELETE_FAILURE";